name: CI - MLflow Training Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'MLProject/**'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  train:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 scikit-learn==1.5.0 \
                      pandas==2.2.2 numpy==1.26.4 matplotlib==3.9.0 seaborn==0.13.2

      - name: Run MLflow Project
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
          MLFLOW_TRACKING_URI: https://dagshub.com/Bimzt/Eksperimen_SML_Bima_Setia.mlflow
        run: |
          cd MLProject
          mlflow run . --env-manager=local \
            -P n_estimators=100 \
            -P max_depth=10 \
            -P min_samples_split=2 \
            -P max_features=sqrt

      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(cat run_id.txt 2>/dev/null || echo "unknown")
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest Run ID: $RUN_ID"

      - name: Upload run_id to GitHub
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add run_id.txt || true
          git diff --staged --quiet || git commit -m "ci: update run_id [skip ci]"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Build Docker Image
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
          MLFLOW_TRACKING_URI: https://dagshub.com/Bimzt/Eksperimen_SML_Bima_Setia.mlflow
        run: |
          mlflow models build-docker \
            --model-uri "runs:/${{ env.RUN_ID }}/model" \
            --name "heart-disease-mlflow"
            --env-manager local

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and Push Docker Image
        run: |
          docker tag heart-disease-mlflow:latest \
            ${{ secrets.DOCKER_USERNAME }}/heart-disease-mlflow:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/heart-disease-mlflow:latest